groups:
  - name: finance
    owner:
      name: Corey 
      email: corey.montano@ucdenver.edu
  - name: marketing
    owner:
      name: Marketing Group
      email: hdc@ucdenver.edu
      
      